stages:
  - build
  - test


variables:
  DOCKER_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  

image: docker:dind

services:
    - docker:dind

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD 

build:
  stage: build
  services:
    - docker:dind
  script:
    - docker build -t $DOCKER_IMAGE .
    - echo $DOCKER_IMAGE
    - echo $CI_COMMIT_REF_SLUG
    - docker images
    - docker push $DOCKER_IMAGE
    #- docker push urielrosen/weather-app:pythonwebapp


test:
  stage: test
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD 
    - docker pull $DOCKER_IMAGE
    - docker run --rm $DOCKER_IMAGE pytest tests/


