stages:
  - build
  - test
  - deploy

variables:
  DOCKER_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  

image: docker:dind

services:
    - docker:dind

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY_URL

build:
  stage: build
  services:
    - docker:dind
  script:
    - sudo docker build -t $DOCKER_IMAGE .
    - sudo docker push $DOCKER_IMAGE


test:
  stage: test
  script:
    - docker run app.py pytest

deploy:
  stage: deploy
  script:
    - echo "Deployment done"
